Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, 
built on top of the Python programming language. It allows you to work with labeled and relational data in an intuitive way.

In [2]:
import pandas as pd # import pandas as pd
pd.set_option('display.width', 1000) # This is to avoid line breaks in the output of the dataframe

In [3]:
# Loading data from a CSV file.
df = pd.read_csv('pokemon_data.csv')

In [4]:
# Print the first 5 rows of the dataframe to get an overview of the data.
print(df.head(5)) # Display the first 5 rows of the dataframe.

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False
4  4             Charmander   Fire     NaN  39      52       43       60       50     65           1      False

In [5]:
print(df.tail(5)) # Display the last 5 rows of the dataframe.

       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
795  719              Diancie     Rock  Fairy  50     100      150      100      150     50           6       True
796  719  DiancieMega Diancie     Rock  Fairy  50     160      110      160      110    110           6       True
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150      130     70           6       True
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170      130     80           6       True
799  721            Volcanion     Fire  Water  80     110      120      130       90     70           6       True

In [6]:
# Reading columns from the dataframe.
print(df.columns) # Display the column names of the dataframe.

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'], dtype='object')

In [7]:
# Displaying specific columns from the dataframe.
print(df['Name']) # Display the 'Name' column of the dataframe.

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [8]:
# Display multiple columns from the dataframe.
print(df[['Name', 'Type 1', 'HP']]) # Display the 'Name', 'Type 1', and 'HP' columns of the dataframe.

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [9]:
# Display each row of the dataframe using iloc.
print(df.iloc[0:4]) # Display the first 4 rows of the dataframe using iloc.

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False

In [10]:
# Read A specific location (Row 2, Column 1) (Name of the 3rd Pokemon)
print(df.iloc[2, 1]) # Display the value at row index 2 and column index 1 of the dataframe.

Venusaur

In [11]:
# Display a filtered column based on a condition.
print(df.loc[df['Type 1'] == 'Fire']) # Display all rows where the 'Type 1' column is equal to 'Fire'.

       #                       Name Type 1    Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4      4                 Charmander   Fire       NaN   39      52       43       60       50     65           1      False
5      5                 Charmeleon   Fire       NaN   58      64       58       80       65     80           1      False
6      6                  Charizard   Fire    Flying   78      84       78      109       85    100           1      False
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111      130       85    100           1      False
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78      159      115    100           1      False
42    37                     Vulpix   Fire       NaN   38      41       40       50       65     65           1      False
43    38                  Ninetales   Fire       NaN   73      76       75       81      100    100           1      False
63    58                  Growlithe   Fire       NaN   55      70       45       70       50     60           1      False
64    59                   Arcanine   Fire       NaN   90     110       80      100       80     95           1      False
83    77                     Ponyta   Fire       NaN   50      85       55       65       65     90           1      False
84    78                   Rapidash   Fire       NaN   65     100       70       80       80    105           1      False
135  126                     Magmar   Fire       NaN   65      95       57      100       85     93           1      False
147  136                    Flareon   Fire       NaN   65     130       60       95      110     65           1      False
158  146                    Moltres   Fire    Flying   90     100       90      125       85     90           1       True
169  155                  Cyndaquil   Fire       NaN   39      52       43       60       50     65           2      False
170  156                    Quilava   Fire       NaN   58      64       58       80       65     80           2      False
171  157                 Typhlosion   Fire       NaN   78      84       78      109       85    100           2      False
236  218                     Slugma   Fire       NaN   40      40       40       70       40     20           2      False
237  219                   Magcargo   Fire      Rock   50      50      120       80       80     30           2      False
259  240                      Magby   Fire       NaN   45      75       37       70       55     83           2      False
263  244                      Entei   Fire       NaN  115     115       85       90       75    100           2       True
270  250                      Ho-oh   Fire    Flying  106     130       90      110      154     90           2       True
276  255                    Torchic   Fire       NaN   45      60       40       70       50     45           3      False
277  256                  Combusken   Fire  Fighting   60      85       60       85       60     55           3      False
278  257                   Blaziken   Fire  Fighting   80     120       70      110       70     80           3      False
279  257      BlazikenMega Blaziken   Fire  Fighting   80     160       80      130       80    100           3      False
352  322                      Numel   Fire    Ground   60      60       40       65       45     35           3      False
353  323                   Camerupt   Fire    Ground   70     100       70      105       75     40           3      False
354  323      CameruptMega Camerupt   Fire    Ground   70     120      100      145      105     20           3      False
355  324                    Torkoal   Fire       NaN   70      85      140       85       70     20           3      False
435  390                   Chimchar   Fire       NaN   44      58       44       58       44     61           4      False
436  391                   Monferno   Fire  Fighting   64      78       52       78       52     81           4      False
437  392                  Infernape   Fire  Fighting   76     104       71      104       71    108           4      False
518  467                  Magmortar   Fire       NaN   75      95       67      125       95     83           4      False
542  485                    Heatran   Fire     Steel   91      90      106      130      106     77           4       True
557  498                      Tepig   Fire       NaN   65      63       45       45       45     45           5      False
558  499                    Pignite   Fire  Fighting   90      93       55       70       55     55           5      False
559  500                     Emboar   Fire  Fighting  110     123       65      100       65     65           5      False
572  513                    Pansear   Fire       NaN   50      53       48       53       48     64           5      False
573  514                   Simisear   Fire       NaN   75      98       63       98       63    101           5      False
614  554                   Darumaka   Fire       NaN   70      90       45       15       45     50           5      False
615  555    DarmanitanStandard Mode   Fire       NaN  105     140       55       30       55     95           5      False
616  555         DarmanitanZen Mode   Fire   Psychic  105      30      105      140      105     55           5      False
692  631                    Heatmor   Fire       NaN   85      97       66      105       66     65           5      False
721  653                   Fennekin   Fire       NaN   40      45       40       62       60     60           6      False
722  654                    Braixen   Fire       NaN   59      59       58       90       70     73           6      False
723  655                    Delphox   Fire   Psychic   75      69       72      114      100    104           6      False
730  662                Fletchinder   Fire    Flying   62      73       55       56       52     84           6      False
731  663                 Talonflame   Fire    Flying   78      81       71       74       69    126           6      False
735  667                     Litleo   Fire    Normal   62      50       58       73       54     72           6      False
736  668                     Pyroar   Fire    Normal   86      68       72      109       66    106           6      False
799  721                  Volcanion   Fire     Water   80     110      120      130       90     70           6       True

In [ ]:
# Describing Data
df.describe() # Display summary statistics of the dataframe.

                #          HP      Attack     Defense     Sp. Atk     Sp. Def       Speed  Generation
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000   800.00000
mean   362.813750   69.258750   79.001250   73.842500   72.820000   71.902500   68.277500     3.32375
std    208.343798   25.534669   32.457366   31.183501   32.722294   27.828916   29.060474     1.66129
min      1.000000    1.000000    5.000000    5.000000   10.000000   20.000000    5.000000     1.00000
25%    184.750000   50.000000   55.000000   50.000000   49.750000   50.000000   45.000000     2.00000
50%    364.500000   65.000000   75.000000   70.000000   65.000000   70.000000   65.000000     3.00000
75%    539.250000   80.000000  100.000000   90.000000   95.000000   90.000000   90.000000     5.00000
max    721.000000  255.000000  190.000000  230.000000  194.000000  230.000000  180.000000     6.00000

In [15]:
# Sorting Data
df.sort_values('Name', ascending=False)

       #                     Name   Type 1  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
794  718         Zygarde50% Forme   Dragon  Ground  108     100      121       81       95     95           6       True
695  634                 Zweilous     Dark  Dragon   72      85       70       65       70     58           5      False
46    41                    Zubat   Poison  Flying   40      45       35       30       40     55           1      False
631  570                    Zorua     Dark     NaN   40      65       40       80       40     65           5      False
632  571                  Zoroark     Dark     NaN   60     105       60      120       60    105           5      False
..   ...                      ...      ...     ...  ...     ...      ...      ...      ...    ...         ...        ...
393  359          AbsolMega Absol     Dark     NaN   65     150       60      115       60    115           3      False
392  359                    Absol     Dark     NaN   65     130       60       75       60     75           3      False
68    63                     Abra  Psychic     NaN   25      20       15      105       55     90           1      False
511  460  AbomasnowMega Abomasnow    Grass     Ice   90     132      105      132      105     30           4      False
510  460                Abomasnow    Grass     Ice   90      92       75       92       85     60           4      False

[800 rows x 12 columns]

In [18]:
# Sorting by multiple columns
df.sort_values(['Type 1', 'Name'], ascending=[False, True]) # Sort by 'Type 1' and then by 'Name' in ascending order.

       #                 Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
655  594            Alomomola  Water     NaN  165      75       80       40       45     65           5      False
199  184            Azumarill  Water   Fairy  100      50       80       60       80     50           2      False
371  339             Barboach  Water  Ground   50      48       43       46       41     60           3      False
610  550             Basculin  Water     NaN   70      92       65       80       55     98           5      False
11     9            Blastoise  Water     NaN   79      83      100       85      105     78           1      False
..   ...                  ...    ...     ...  ...     ...      ...      ...      ...    ...         ...        ...
459  413  WormadamSandy Cloak    Bug  Ground   60      79      105       59       85     36           4      False
460  413  WormadamTrash Cloak    Bug   Steel   60      69       95       69       95     36           4      False
288  265              Wurmple    Bug     NaN   45      45       35       20       30     20           3      False
208  193                Yanma    Bug  Flying   65      65       45       75       45     95           2      False
520  469              Yanmega    Bug  Flying   86      76       86      116       56     95           4      False

[800 rows x 12 columns]

In [19]:
# Making changes to the data
print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False
4  4             Charmander   Fire     NaN  39      52       43       60       50     65           1      False

In [21]:
# Adding a new column to the dataframe
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False    318
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False    405
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False    525
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False    625
4  4             Charmander   Fire     NaN  39      52       43       60       50     65           1      False    309

In [ ]:
# Dropping a column
df = df.drop(columns=['Total']) # Have to store this in a var because drop() does not modify the dataframe in place, meaning the original dataframe remains unchanged unless reassigned.

print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False
4  4             Charmander   Fire     NaN  39      52       43       60       50     65           1      False

In [26]:
# Adding Total column via iloc
df['Total'] = df.iloc[:, 4:10].sum(axis=1) # axis = 1 means summing across columns for each row instead of down the columns

print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total
0  1              Bulbasaur  Grass  Poison  45      49       49       65       65     45           1      False    318
1  2                Ivysaur  Grass  Poison  60      62       63       80       80     60           1      False    405
2  3               Venusaur  Grass  Poison  80      82       83      100      100     80           1      False    525
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122      120     80           1      False    625
4  4             Charmander   Fire     NaN  39      52       43       60       50     65           1      False    309

In [29]:
# Move a column to a different position
col = df.pop('Total') # Remove the column from its current position
df.insert(4, 'Total', col) # Insert the column at the desired position (index 4 in this case)

print(df.head(5))

   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison    318  45      49       49       65       65     45           1      False
1  2                Ivysaur  Grass  Poison    405  60      62       63       80       80     60           1      False
2  3               Venusaur  Grass  Poison    525  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123      122      120     80           1      False
4  4             Charmander   Fire     NaN    309  39      52       43       60       50     65           1      False

In [ ]:
# Saving our data
# df.to_csv('modified_pokemon_data.csv', index=False) # Save the dataframe to a CSV file without the index column

In [38]:
# Filtering data
filtered_total = df[df['Total'] > 700] # Example: filter rows where the 'Total' column is greater than 500

print(filtered_total)

       #                   Name   Type 1    Type 2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
163  150    MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190      100      154      100    130           1       True
164  150    MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150       70      194      120    140           1       True
422  382    KyogrePrimal Kyogre    Water       NaN    770  100     150       90      180      160     90           3       True
424  383  GroudonPrimal Groudon   Ground      Fire    770  100     180      160      150       90     90           3       True
426  384  RayquazaMega Rayquaza   Dragon    Flying    780  105     180      100      180      100    115           3       True
552  493                 Arceus   Normal       NaN    720  120     120      120      120      120    120           4       True

In [ ]:
# Filtering data on multiple conditions
filtered_multiple = df[(df['Total'] > 700) & (df['HP'] > 105)] # Example: filter rows where 'Total' is greater than 700 and 'HP' is greater than 105
filtered_multiple = filtered_multiple.reset_index(drop=True) # Drop = True means the old index is not added as a column

print(filtered_multiple)

     #                 Name   Type 1    Type 2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  150  MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190      100      154      100    130           1       True
1  150  MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150       70      194      120    140           1       True
2  493               Arceus   Normal       NaN    720  120     120      120      120      120    120           4       True

In [ ]:
# Regex filtering
regex_filtered = df[df['Type 1'].str.contains('Fire|Water', regex=True)] 

print(regex_filtered)

       #                       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4      4                 Charmander   Fire     NaN    309  39      52       43       60       50     65           1      False
5      5                 Charmeleon   Fire     NaN    405  58      64       58       80       65     80           1      False
6      6                  Charizard   Fire  Flying    534  78      84       78      109       85    100           1      False
7      6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111      130       85    100           1      False
8      6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78      159      115    100           1      False
..   ...                        ...    ...     ...    ...  ..     ...      ...      ...      ...    ...         ...        ...
735  667                     Litleo   Fire  Normal    369  62      50       58       73       54     72           6      False
736  668                     Pyroar   Fire  Normal    507  86      68       72      109       66    106           6      False
762  692                  Clauncher  Water     NaN    330  50      53       62       58       63     44           6      False
763  693                  Clawitzer  Water     NaN    500  71      73       88      120       89     59           6      False
799  721                  Volcanion   Fire   Water    600  80     110      120      130       90     70           6       True

[164 rows x 13 columns]

In [52]:
# Conditional changes
# Changing 'fire' to 'flamer'
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

print(df.head(5))

   #                   Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur   Grass  Poison    318  45      49       49       65       65     45           1      False
1  2                Ivysaur   Grass  Poison    405  60      62       63       80       80     60           1      False
2  3               Venusaur   Grass  Poison    525  80      82       83      100      100     80           1      False
3  3  VenusaurMega Venusaur   Grass  Poison    625  80     100      123      122      120     80           1      False
4  4             Charmander  Flamer     NaN    309  39      52       43       60       50     65           1      False

In [13]:
# Aggregate statistics
mean_total = df['Total'].mean() # Calculate the mean of the 'Total' column
max_total = df['Total'].max() # Calculate the maximum of the 'Total' column
min_total = df['Total'].min() # Calculate the minimum of the 'Total' column
sum_total = df['Total'].sum() # Calculate the sum of the 'Total' column

print(f"Mean Total: {mean_total}")
print(f"Max Total: {max_total}")
print(f"Min Total: {min_total}")
print(f"Sum Total: {sum_total}")

NameError: name 'df' is not defined